# Generated by Django 3.1.1 on 2020-10-05 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('SubCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='API.subcategoria')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.cliente')),
            ],
        ),
    ]
