# Generated by Django 3.1.1 on 2020-10-05 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_solicitud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='SubCategoria',
            new_name='subCategoria',
        ),
    ]
