# Generated by Django 3.1.1 on 2020-10-05 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20201005_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='subCategoria',
            new_name='subcategoria',
        ),
    ]
