# Generated by Django 3.1.1 on 2020-10-06 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20201005_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='subcategoria',
            new_name='subCategoria',
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.cliente'),
        ),
    ]
