# Generated by Django 3.1.1 on 2020-09-25 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20200925_0203'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BannersPublicitarios',
            new_name='BannerPublicitario',
        ),
    ]
