# Generated by Django 3.1.1 on 2020-10-06 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20201006_0221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='subCategoria',
            new_name='subcategoria',
        ),
    ]
